---
# FILE:            playbooks/roles/ckan/tasks/install.yml
# LICENSE:         Public Domain

- name: "CKAN | Install {{ ckan_package_url }}"
  apt:
    deb: "{{ ckan_package_url }}"
    # install_recommends: no
