---
# FILE:            playbooks/roles/ckan/tasks/main.yml
# LICENSE:         Public Domain
# SEE:             https://docs.ckan.org/en/2.8/maintaining/installing/install-from-package.html
# SEE:             https://docs.ckan.org/en/2.8/maintaining/installing/install-from-source.html

# tail -f /var/log/apache2/ckan_default.error.log
# vim /etc/ckan/default/production.ini

- name: Ubuntu?
  fail:
    msg: "This role as designed to only Ubuntu 18.04. Please look for other alternatives"
  when: ansible_distribution != 'Ubuntu'

# # SEE http://packaging.ckan.org/
# - name: "ping all"
#   ping:
#     data: pong

- name: "Check if /etc/ckan/default/production.ini exists"
  stat:
    path: "/etc/ckan/default/production.ini"
  register: stat_result

- debug: var=stat_result

- name: "install.yml"
  include: install.yml
  when:
    - "(not stat_result.stat.exists) or (ckan_force_reinstall|bool)"

- name: "configure.yml"
  include: configure.yml
  # when:
  #   - "(not stat_result.stat.exists) or (ckan_force_reinstall|bool)"
