---
# FILE:            playbooks/roles/traefik/tasks/configure.yml
# LICENSE:         Public Domain

# TODO: implement traefik.toml template (fititnt, 2020-04-05 11:08 BRT)

# - name: "Deploy traefik.toml"
#   template:
#     src: "traefik.yml.j2"
#     dest: "/etc/traefik/traefik.toml"
#     mode: 0664
#     block_start_string: "[[[%"
#     block_end_string: "%]]]"
#     variable_start_string: "[[["
#     variable_end_string: "]]]"
#   notify:
#     - reload traefik

- name: "Deploy /etc/traefik/traefik.yml"
  template:
    src: "{{ traefik_conf_yml }}"
    dest: "/etc/traefik/traefik.yml"
    mode: 0664
    # block_start_string: "[[[%"
    # block_end_string: "%]]]"
    # variable_start_string: "[[["
    # variable_end_string: "]]]"
  notify:
    - reload traefik

- name: "Copy files from [[ traefik_conf_dinamyc_files ]] on /etc/traefik/traefik.d/"
  copy:
    src: "{{ item.src }}"
    dest: "/etc/traefik/traefik.d/{{ item.name }}"
    mode: 0664
  with_items: "{{ traefik_conf_dinamyc_files }}"
  when:
    - "(traefik_conf_dinamyc_files is defined) and (traefik_conf_dinamyc_files|length > 0)"
    - "(item.state is not defined) or (item.state != 'absent')"

- name: "Delete files [[ traefik_conf_dinamyc_files ]] /etc/traefik/traefik.d/ if state=absent"
  file:
    dest: "/etc/traefik/traefik.d/{{ item.name }}"
    state: absent
  with_items: "{{ traefik_conf_dinamyc_files }}"
  when:
    - "(traefik_conf_dinamyc_files is defined) and (traefik_conf_dinamyc_files|length > 0)"
    - "(item.state is defined) and (item.state == 'absent')"
