---
# FILE:            playbooks/roles/traefik/tasks/install.yml
# LICENSE:         Public Domain

- name: "Create traefik_temp_dir"
  tempfile:
    state: directory
    suffix: traefik_temp_dir
  register: traefik_temp_dir

- name: "Create /etc/traefik/ it does not exist"
  file:
    path: "/etc/traefik/"
    state: directory
    mode: '0755'
  become: yes

- name: "Create /etc/traefik/traefik.d/ it does not exist"
  file:
    path: "/etc/traefik/traefik.d/"
    state: directory
    mode: '0755'
  become: yes

- name: "Create /var/log/traefik/ it does not exist"
  file:
    path: "/var/log/traefik/"
    state: directory
    mode: '0755'
  become: yes

# TODO: implement logrotation (fititnt, 2020-04-07 04:43 BRT)
- name: "Create /var/log/traefik/access.log it does not exist"
  file:
    path: "/var/log/traefik/access.log"
    state: touch
    mode: '0664'
  # become: yes

- name: "Create /etc/traefik/acme.json it does not exist"
  file:
    path: "/etc/traefik/acme.json"
    state: touch
    mode: '0600'
  # become: yes

- name: "Download {{ traefik_download_url }}"
  unarchive:
    src: "{{ traefik_download_url }}"
    dest: "{{ traefik_temp_dir.path }}"
    remote_src: yes

- name: "Move to {{ traefik_install_base }}"
  copy:
    src: "{{ traefik_temp_dir.path }}/traefik"
    dest: "{{ traefik_install_base }}"
    remote_src: yes
    mode: "0755"

- name: "Create systemd service"
  template:
    # src: "traefik.service.j2"
    src: "{{ traefik_systemd_service_template | default('traefik.service.j2') }}"
    dest: "/etc/systemd/system/traefik.service"
    mode: 0664
  notify:
    - "restart traefik"
