---
# FILE:            playbooks/docker-ckan-stack-start.yml
# LICENSE:         Public Domain
# DESCRIPTION:     Install CKAN with docker-compose
#
# DEPRECATED:      WARNING! This file is deprecated and not used. It will
#                  stay here just as reference (fititnt, 2020-04-12 16:02 BRT)

# ansible-playbook -i inventories/etica.dev playbooks/docker-ckan-stack-start.yml

# @see https://github.com/docker/compose/issues/6361#issuecomment-462346569

- name: "docker-ckan-stack-start"
  hosts: all
  gather_facts: yes
  tasks:

    - name: "docker-ckan-stack-start | Copy docker/ckan-stack/ to [ansible user home]/ckan-stack/"
      copy:
        src: "{{ playbook_dir }}/../../docker/ckan-stack/"
        dest: "{{ ansible_env.HOME }}/ckan-stack/"

    - name: "docker-ckan-stack-start | start services"
      docker_compose:
        project_src: "{{ ansible_env.HOME }}/ckan-stack/"
        state: present
        services:
          - ckan
          - datapusher
          - db
          - solr
          - redis
      register: output

    - name: "docker-ckan-stack-start | services result"
      debug:
        msg: "{{ output }}"
