---
# FILE:            playbooks/docker-full-stack-start.yml
# LICENSE:         Public Domain
# DESCRIPTION:     
#
# REQUIRES:       pip install docker

# ansible-playbook -i inventories/etica.dev playbooks/docker-full-stack-start.yml

# @see https://github.com/docker/compose/issues/6361#issuecomment-462346569

- name: "docker-full-stack-start"
  hosts: all
  gather_facts: yes
  tasks:
    # - name: Tear down existing services
    #   docker_compose:
    #     project_src: flask
    #     state: absent

    # - name: "docker-full-stack-start | debug"
    #   debug:
    #     msg: "{{ playbook_dir }}/../../docker/full-stack/"
    #     # var: "{{ playbook_dir }}/../../docker/full-stack/"

    - name: "docker-full-stack-start| Copy docker/full-stack/ to [ansible user home]/full-stack/"
      copy:
        src: "{{ playbook_dir }}/../../docker/full-stack/"
        dest: "{{ ansible_env.HOME }}/full-stack/"

    - name: "docker-full-stack-start | start services"
      docker_compose:
        project_src: "{{ ansible_env.HOME }}/full-stack/"
        state: present
        services:
          - hello
          - hxl-proxy
      register: output

    - name: "docker-full-stack-start | services result"
      debug:
        msg: "{{ output }}"
