---
# FILE:            playbooks/redis.yml
# LICENSE:         Public Domain
# DESCRIPTION:     Install redis on the host.
#                  It's used by CKAN. You can skip this playbook
# SEE:             https://github.com/DavidWittman/ansible-redis

# ansible-playbook -i inventories/etica.dev playbooks/redis.yml

- hosts: all
  vars:
    - redis_bind: 127.0.0.1
      redis_version: 5.0.8
      redis_verify_checksum: true
      # See https://github.com/antirez/redis-hashes
      redis_checksum: "sha256:f3c7eac42f433326a8d981b50dba0169fdfaf46abb23fcda2f933a7552ee4ed7"
  roles:
    - davidwittman.redis
