---
# FILE:            inventories/etica.dev/hosts.yml
# LICENSE:         Public Domain
# DESCRIPTION:     This is an Ansible inventory file.
#                  We will use as test server the server hxl.etica.dev

# SEE:             https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html

all:
  hosts:
    hxl_eticadev:
      # IPv4: 144.91.108.24
      ansible_host: hxl.etica.dev
      ansible_python_interpreter: "/usr/bin/python3"

  children:
    hxl_servers:
      hosts:
        hxl_eticadev:

  vars:

    # traefik_version: "2.2.0"
    # traefik_arch: "linux_amd64"
    ## To force reinstall / update the traefik, please set this to yes
    # traefik_force_reinstall: yes
    # traefik_force_reinstall: yes
    traefik_debug_devel: yes

    # @see https://github.com/geerlingguy/ansible-role-pip#role-variables
    # By default, geerlingguy.pip will use pip from python 2.7.
    # You can force on your inventory use another pip. On case of
    # Ubuntu 18.04, you can explicitly force the pip package and pip executable:
    pip_package: "python3-pip"
    pip_executable: "pip3"
