---
# FILE:            inventories/etica.dev/hosts.yml
# LICENSE:         Public Domain
# DESCRIPTION:     This is an Ansible inventory file.
#                  We will use as test server the server hxl.etica.dev

# SEE:             https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html

all:
  hosts:
    hxl_eticadev:
      # IPv4: 144.91.108.24
      ansible_host: hxl.etica.dev
      ansible_python_interpreter: "/usr/bin/python3"

  children:
    hxl_servers:
      hosts:
        hxl_eticadev:
