---
# defaults file for traefik

# Check https://github.com/containous/traefik/releases for updates

traefik_version: "2.2.0"
traefik_arch: "linux_amd64"

# traefik_download_url: "https://github.com/containous/traefik/releases/download/v2.2.0/traefik_v2.2.0_linux_amd64.tar.gz"
traefik_download_url: "https://github.com/containous/traefik/releases/download/v{{ traefik_version }}/traefik_v{{ traefik_version }}_{{ traefik_arch }}.tar.gz"
