---
# FILE:            playbook.yml
# LICENSE:         Public Domain
# DESCRIPTION:     This is an Ansible main playbook. It call all other
#                  sub-playbooks in a order to make an full preparation of the
#                  host that will run the docker containers

# ansible-playbook -i inventories/etica.dev playbook.yml
- import_playbook: playbooks/ping-all.yml
- import_playbook: playbooks/common.yml
- import_playbook: playbooks/traefik.yml
- import_playbook: playbooks/docker-setup-host.yml
- import_playbook: playbooks/docker-full-stack-start.yml
- import_playbook: playbooks/postgresql.yml
