---
# FILE:            requirements.yml
# LICENSE:         Public Domain
# DESCRIPTION:     The requirements.yml may be used by ansible-galaxy command
#                  to install Ansible roles that are used by Ansible playbooks
#
# USAGE:           ansible-galaxy install -r requirements.yml

# https://github.com/geerlingguy/ansible-role-docker
- src: geerlingguy.docker
  # Tested with v2.7.0, 2020-04-05

# https://github.com/geerlingguy/ansible-role-pip
- src: geerlingguy.pip
  # Tested with v1.3.0, 2018-11-10

# https://github.com/geerlingguy/ansible-role-postgresql
- src: geerlingguy.postgresql
  # Tested with v2.2.0, 2020-03-20

- src: geerlingguy.java
  # Tested with v1.9.7

# https://github.com/geerlingguy/ansible-role-solr
- src: geerlingguy.solr
  # Tested with v5.1.0

# https://github.com/DavidWittman/ansible-redis
- src: davidwittman.redis
  # Tested with v1.2.7
