version: "3"

# See https://docs.docker.com/compose/django/
# @see https://github.com/bubelov/traefik-letsencrypt-compose/blob/master/docker-compose.yml
# @see https://containo.us/blog/traefik-2-0-docker-101-fc2893944b9d/

services:
  # hxldash:
  
  # hello:
  #   image: nginxdemos/hello
  #   labels:
  #     - traefik.http.routers.http.rule=Host(`hello.hxl.etica.dev`)
  #     - traefik.http.routers.https.rule=Host(`hello.hxl.etica.dev`)
  #     - traefik.http.routers.https.entrypoints=https
  #     - traefik.http.routers.https.tls=true
  #     # - traefik.http.routers.https.tls.certresolver=letsencrypt

  whoami:
    image: containous/whoami
    container_name: whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.hxl.etica.dev`)"
      - "traefik.http.routers.whoami.entrypoints=web,websecure"
      - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"
      # TODO: implement middleware 'redirect HTTP to HTTPS' (fititnt, 2020-04-07 00>39 BRT)
      # - "traefik.http.routers.http.middlewares=redirect"

  # TODO: make it work
  # @see https://github.com/HXLStandard/hxl-proxy/blob/master/docker_files/docker-compose.yml
  hxl-proxy:
    # image: unocha/hxl-proxy:dev
    image: unocha/hxl-proxy:1.18 # see https://hub.docker.com/r/unocha/hxl-proxy/tags
    # command: python manage.py runserver 0.0.0.0:8000
    # depends_on:
    #   - postgres_hxl-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hxl-proxy.rule=Host(`proxy.hxl.etica.dev`)"
      - "traefik.http.routers.hxl-proxy.entrypoints=web,websecure"
      - "traefik.http.routers.hxl-proxy.tls.certresolver=letsencrypt"
      # TODO: implement middleware 'redirect HTTP to HTTPS' (fititnt, 2020-04-07 00>39 BRT)
      # - "traefik.http.routers.http.middlewares=redirect"

  # postgres_hxl-proxy:
  #   image: postgres
